INSERT INTO `PACCHETTI` (`nome`, `descrizione`, `sotto_descrizione`, `immagine`, `tipologia`, `prezzo`)
VALUES
		('Glacier Express','Sette ore e mezzo di viaggio tra 290 ponti e incredibili paesaggi alpini. Si parte a St.Moritz e si raggiunge Zermatt viaggiando in confortevoli carrozze panoramiche lungo i tragitti ferroviari di montagna più belli del mondo, nelle gole del Reno.','-un’avventura nella Svizzera incontaminata-','http://localhost/HW1/foto/pacchetti/europa/eu1.jpg','europa','3000'),
        ('Belmond Royal Scotsman','Viaggiare in questo treno è davvero un’esperienza unica: laghi, cascate, spiagge, castelli della bella Scozia scorrono affianco a te, mentre sul treno potrai gustare cene stellate e ascoltare della musica live, gustando il tè delle cinque.','-la Scozia delle Highlands-','http://localhost/HW1/foto/pacchetti/europa/eu2.jpg','europa','2000'),
        ('Il Treno delle Meraviglie','Da scenari di montagna al profumo del mare, dalle escursioni alpine alle passeggiate lungomare, in mezzo paesaggi indimenticabili e suggestivi: è questa la ferrovia Cuneo-Ventimiglia, un percorso romantico che parte dal Piemonte e arriva in Liguria, passando per la Francia.','-tra Francia e Italia-','http://localhost/HW1/foto/pacchetti/europa/eu3.jpg','europa','2500'),
        ('Bergen Railway','Nella nostra classifica non poteva certo mancare questo moderno treno che permette di raggiungere Bergen dalla capitale norvegese, Oslo. Si attraversa uno degli altipiani più alti d’Europa, scoprendo paesaggi davvero incredibili.','-l’essenza della Norvegia-','http://localhost/HW1/foto/pacchetti/europa/eu4.jpg','europa','3200'),
        ('Tunnel of Love','Questo è certamente il treno più romantico del mondo. Cinque brevi chilometri di ferrovia da Klevan a Orzhiv in Ucraina, e tre chilometri nel famosissimo Tunnel dell’Amore, un intreccio di alberi e vegetazione che crea uno scenario suggestivo e romantico, quasi irreale, un luogo di promesse d’amore e baci rubati.','-una ferrovia da favola-','http://localhost/HW1/foto/pacchetti/europa/eu5.jpg','europa','4000'),
        ('La Circumetnea','Un modo originale per visitare uno dei simboli siciliani: l’Etna. La storica ferrovia è stata inaugurata nel 1898 e viaggia intorno al vulcano attraversando numerosi paesini, regalando ai viaggiatori pittoreschi scorci di questo paesaggio unico.','-tra i paesaggi lavici-','http://localhost/HW1/foto/pacchetti/europa/eu6.jpg','europa','1500'),
		('Shangri-La Express', 'Un tour a bordo del Shangri-La Express alla scoperta dei paesaggi incontaminati della Cina, dei suoi panorami sterminati e delle sue antiche città, addentrandosi sino in Tibet tra i picchi himalayani che vi porteranno sul “tetto del mondo”! Scegliete un modo unico di vivere un viaggio indimenticabile!', '-Cina E Tibet Rail Discovery-', 'http://localhost/HW1/foto/pacchetti/asia/shangri-la-express.jpg', 'asia', '9895'),
        ('Belmond Eastern & Oriental Express', 'Due città vibranti, scenari rurali da cartolina, charme e atmosfere sospese… I binari conducono al cuore della tradizione e dell’autentico, mentre a bordo si vive un’esperienza straordinaria ed esclusiva, con uno stile ed un’eleganza senza eguali.', '-Bangkok - Singapore-', 'http://localhost/HW1/foto/pacchetti/asia/Eastern-Oriental-Express-0.png', 'asia', '3200'),
        ('Maharajas Express', "Attraversare i magici paesaggi, angoli e tesori che contraddistinguono New Delhi, Jaipur ed Agra, tra le destinazioni più incantevoli del mondo Indiano. Immergiti in luoghi in cui capolavori dell’uomo si fondono con una natura mozzafiato. Scopri antichi riti, culture e tradizioni!", "-Tesori Dell'India-", 'http://localhost/HW1/foto/pacchetti/asia/Treno-Maharaja-Express-Tesori-India-.jpg', 'asia', '3600'),
        ('Golden Eagle Express', "Un viaggio da Pechino a Mosca per rievocare miti, racconti ed atmosfere di una delle più importanti vie commerciali della storia. Per secoli, mercanti e avventurieri hanno attraversato il continente asiatico, lungo i suoi paesaggi aspri ma di estremo fascino, trasportando pregiate sete, spezie e profumi. Questa è la Via della Seta, 6400 km di pura bellezza.", '-Via Della Seta Pechino - Mosca-', 'http://localhost/HW1/foto/pacchetti/asia/golden-eagle-silk-road-grande-muraglia-960x1149.jpg', 'asia', '22.995'),
        ('Orient Silk Road Express', "Un viaggio nella bellezza attraverso tre paesi e sette Patrimoni Unesco. Un viaggio nella storia tra antichi miti e storie perse nei meandri del tempo. Un viaggio che incanta, come le favole delle Mille e Una Notte… Questa è la Via della Seta: 6400 km di pura bellezza.", '-Almaty - Ashgabat-', 'http://localhost/HW1/foto/pacchetti/asia/orient%20silk%20road%20express.jpeg', 'asia', '3.120'),
        ("Tsar's Gold", "L’inverno trasforma i paesaggi di Russia e Mongolia in candidi scenari da favola, dando quel tocco in più ad un viaggio già di per sè incantevole. Tsar’s Gold vi porta sulla Transiberiana innevata alla scoperta della magia dell’Asia d’inverno! Prolugate il viaggio fino a Pechino per scoprire anche una delle capitali più antiche del mondo ricoperta di neve…", "-Favola D'Inverno Sulla Transiberiana-", 'http://localhost/HW1/foto/pacchetti/asia/cristo-salvatore-innevata-960x1149.jpg', 'asia', '3.420'),
		("Rovos Rail", "Il viaggio Dar Es Salaam – Cape Town è epico, ricco di emozionanti scoperte, in grado di arricchire il bagaglio del proprio spirito viaggiatore. La magia di Sudafrica, Botswana, Zimbabwe, Zambia e Tanzania, in un turbinio di luci e colori che dipingono paesaggi indimenticabili, attraverso cui solo l’esperienza su rotaia riesce a dar vita a quell’atmosfera sospesa nel tempo e d’intimità con la natura… lasciati incantare!", "-Dar Es Salaam - Cape Town-", "http://localhost/HW1/foto/pacchetti/africa/RR%20Rail%20balcone%20osservatorio%20ok%20%20itin.jpg", "africa", "11.990"),
        ("Shongololo Express", "Il viaggio Dune Express da Walvis Bay a Pretoria è un’avventura unica. A bordo dello Shongololo Express si parte da Walvis Bay per attraversare le dune più selvagge della Namibia, pernottando due notti in lodge in questa magnifica area deserta sulle coste dell’Atlantico. Un viaggio esperienziale all’insegna dei safari nei parchi Etosha e Namib-Naukluft per avvistare le specie più caratteristiche, esplorando la città fantasma circondata dalla sabbia del deserto e il Fish River Canyon, il canyon più esteso dell’emisfero meridionale. Un’avventura che termina nel cuore del Sudafrica nella città di Pretoria: impossibile non concluderla senza provare il celebre “mal d’Africa”…", "-Walvis Bay - Pretoria-", "http://localhost/HW1/foto/pacchetti/africa/RVR-GardenRteBrakRiver2-LRes-2-960x1149.jpg", "africa", "5.380"),
        ("African Explorer", "Il viaggio Cascate Vittoria – Pretoria è un tuffo nella natura selvaggia, un susseguirsi di incontri ravvicinati con le maestose creazioni della natura africana, una fusione di contrasti e tradizioni attraverso gli scenari di Zimbabwe, Sudafrica, Mozambico e Swaziland. Esperienze esclusive ed indimenticabili: safari notturni, vivaci mercati, pendii mozzafiato, centri di salvaguardia, fragorose cascate… salite a bordo dell’African Explorer e risvegliate i vostri sensi!", "-Cascate Vittoria - Pretoria-", "http://localhost/HW1/foto/pacchetti/africa/VictoriaFalls_natureimmortal-960x1149.jpg", "africa", "5.150"),
        ("Rovos Rail", "Attraversare il nord-est del Sudafrica con un itinerario speciale: il Golf Safari si suddivide in 2 programmi, uno riservato ai golfisti con numerose giornate dedicate al gioco in alcuni fra i migliori campi del Paese e un altro rivolto a chi non pratica questa disciplina con straordinarie esperienze per scoprire le meraviglie del territorio. Da Pretoria a Sun City con il Parco Nazionale Pilanesberg, proseguendo verso le Drakensberg Mountains e Spionkop, attraversando la scenografica Valle delle Mille Colline fino a Durban, raggiungendo il Parco di Hluhluwe, la riserva di Mkhaya e il celebre Kruger Park prima di rientrare a Pretoria.", "-Golf Safari-", "http://localhost/HW1/foto/pacchetti/africa/rovos-rail-treno-luxurytrain-people-960x1149.jpg", "africa", "3.970"),
        ("Rovos Rail", "Il Golf African Collage da Cape Town a Pretoria, attraversa il sud e nord-est del Sudafrica con un itinerario speciale. Questo Golf Safari si suddivide in 2 programmi, uno riservato ai golfisti con numerose giornate dedicate al gioco in alcuni fra i migliori campi del Paese e un altro rivolto a chi non pratica questa disciplina con straordinarie esperienze per scoprire le meraviglie del territorio. Da Cape Town, città madre, passando dalla laguna di Knysna, Port Elizabeth e Spionkop, per poi visitare i meravigliosi parchi Hluhluwe e Kruger con la loro ricca fauna, terminando l’itinerario a Pretoria.", "-Golf African Collage Cape Town - Pretoria-", "http://localhost/HW1/foto/pacchetti/africa/RVR-PaarlWesternCape-LRes-960x1149.jpg", "africa", "4.770"),
        ("Rovos Rail", "Il Safari in Namibia Walvis Bay – Pretoria è ricco di emozionanti scoperte, in grado di arricchire il bagaglio di ogni viaggiatore. La magia dei paesaggi namibiani, in un turbinio di luci e colori che dipingono panorami indimenticabili, attraverso cui solo l’esperienza su rotaia riesce a creare quell’atmosfera sospesa nel tempo e d’intimità con la natura… lasciatevi incantare!", "-Safari In Walvis Bay - Pretoria-", "http://localhost/HW1/foto/pacchetti/africa/elefanti-nel-vlei-960x1149.jpg", "africa", "4.680"),
		("Belmond Andean Explorer", "Vivi le emozioni della rotta più affascinante del Perù: Cuzco, l’ “Ombelico del Mondo”, capitale dello splendente Impero Inca; Puno ed il Lago Titicaca, luci e suggestioni tra gli altopiani andini; Arequipa, vulcani e bianchi edifici coloniali; il Canyon del Colca, un susseguirsi di aspri, pungenti e romantici scenari, colorati dai bagliori dell’alba e dalle sfumature teatrali del tramonto.", "-Cuzco - Arequipa-", "http://localhost/HW1/foto/pacchetti/america/belmond-andean-explorer-treno-peru-960x1149.jpg", "america", "1.660"),
        ("East Coast", "Il viaggio inizia da Washington, epicentro politico del paese e famosa per i suoi parchi, prosegue verso Philadelphia, ricca di storia e dove si trova la Liberty Bell, simbolo dell’indipendenza americana. Il tour si conclude a New York, la metropoli per eccellenza, dove camminare per le brulicanti strade e visitare gli innumerevoli musei. Da una città all’altra con il treno, per apprezzare al meglio anche gli spostamenti.", "- da Washington a New York passando per Philadelphia-", "http://localhost/HW1/foto/pacchetti/america/in-treno-nella-east-coast-cover.jpg", "america", "8.550"),
        ("EMPIRE BUILDER", "L’itinerario dell’Empire Builder è davvero un viaggio iconico, in particolare per gli appassionati di storia e avventura, perché esplora gli Stati Uniti nordoccidentali, attraverso le Cascade Mountains e lungo la Columbia River Gorge. Questo percorso ripercorre le orme degli esploratori Lewis e Clark nella storica spedizione attraverso le Rockies e il Continental Divide, dove il treno corre a 1590 m sul livello del mare. Il treno si ferma alla Glacier Park Station, adiacente ai ghiacciai “viventi” e alle cime innevate del Glacier National Park, per una vista davvero incredibile sulle montagne. Questa fantastica esperienza con l’Empire Builder di Amtrak parte da Chicago – Illinois e dopo aver attraversato gli Stati Uniti nordoccidentali, si conclude sulle rive dell’oceano Pacifico, a Seattle, stato di Washington", "- L’itinerario Infinito-", "http://localhost/HW1/foto/pacchetti/america/empire-builder.jpg", "america", "2.300"),
        ("CALIFORNIA ZEPHYR", "La rotta del California Zephyr offre alcuni dei panorami più spettacolari del paese, che rappresentano il meglio del cuore dell’America da Chicago a Denver e pittoreschi paesaggi desertici da Denver alla California. Fai un giro in tutta comodità lungo le pendici delle Rocky Mountains, attraverso i deserti dello Utah e delle High Sierras, e raggiungi la “City by the Bay”, San Francisco. A bordo di Zephyr, carrozze Superliner a due piani, rilassati nel massimo comfort mentre osservi il paesaggio che scorre. Il treno offre posti letto, ristoranti e punti ristoro per rendere la tua esperienza davvero confortevole.", "-La Rotta Panoramica-", "http://localhost/HW1/foto/pacchetti/america/california-zephyr.jpg", "america", "5.500"),
        ("SOUTHWEST CHIEF", "La rotta del Southwest Chief parte da Chicago, attraversa il Mississippi e altri otto stati ripercorrendo il leggendario West americano, e termina la sua corsa a Los Angeles, offrendo ai passeggeri panorami e paesaggi non accessibili dalle autostrade interstatali. Attraversa campi coltivati, montagne e deserti e curva attraverso stretti passaggi di canyon di roccia rossa e infine si snoda attraverso il terreno accidentato del New Mexico e dell’Arizona. A bordo del Southwest Chief, potrai goderti il Superliner, pernottamenti e ristoranti a due piani e spettacolari viste dal pavimento al soffitto nella famosa carrozza con vetrata panoramica: Sightseer Lounge Car.", "- Mississippi - West americano-", "http://localhost/HW1/foto/pacchetti/america/Southwest-Chief-2.jpg", "america", "3.750"),
        ("COAST STARLIGHT", "Il Coast Starlight di Amtrak è considerato uno dei viaggi in treno panoramici tra i più belli del paese. Offre le migliori viste della costa del Pacifico, dalle scogliere della Pacific Coast Highway alle cime delle Cascade Mountains. Il percorso collega le città più famose lungo la costa occidentale - Los Angeles, Santa Barbara, San Francisco, Sacramento e Portland - offrendo fermate memorabili lungo il percorso. A bordo, guarda le foreste lussureggianti, le fertili vallate e le lunghe distese dell’Oceano Pacifico dal comfort dei sedili del Superliner e della Sightseer Lounge Car.", "-Pacific Coast Highway - Cascade Mountains-", "http://localhost/HW1/foto/pacchetti/america/COAST%20STARLIGHT.jpg", "america", "4.790");


INSERT INTO `PACCHETTI` (`nome`, `descrizione`, `sotto_descrizione`, `immagine`, `tipologia`, `prezzo`)
VALUES
		('Glacier Express','Sette ore e mezzo di viaggio tra 290 ponti e incredibili paesaggi alpini. Si parte a St.Moritz e si raggiunge Zermatt viaggiando in confortevoli carrozze panoramiche lungo i tragitti ferroviari di montagna più belli del mondo, nelle gole del Reno.','-un’avventura nella Svizzera incontaminata-','http://localhost/HW1/foto/pacchetti/europa/eu1.jpg','europa','3000'),
        ('Belmond Royal Scotsman','Viaggiare in questo treno è davvero un’esperienza unica: laghi, cascate, spiagge, castelli della bella Scozia scorrono affianco a te, mentre sul treno potrai gustare cene stellate e ascoltare della musica live, gustando il tè delle cinque.','-la Scozia delle Highlands-','http://localhost/HW1/foto/pacchetti/europa/eu2.jpg','europa','2000'),
        ('Il Treno delle Meraviglie','Da scenari di montagna al profumo del mare, dalle escursioni alpine alle passeggiate lungomare, in mezzo paesaggi indimenticabili e suggestivi: è questa la ferrovia Cuneo-Ventimiglia, un percorso romantico che parte dal Piemonte e arriva in Liguria, passando per la Francia.','-tra Francia e Italia-','http://localhost/HW1/foto/pacchetti/europa/eu3.jpg','europa','2500'),
        ('Bergen Railway','Nella nostra classifica non poteva certo mancare questo moderno treno che permette di raggiungere Bergen dalla capitale norvegese, Oslo. Si attraversa uno degli altipiani più alti d’Europa, scoprendo paesaggi davvero incredibili.','-l’essenza della Norvegia-','http://localhost/HW1/foto/pacchetti/europa/eu4.jpg','europa','3200'),
        ('Tunnel of Love','Questo è certamente il treno più romantico del mondo. Cinque brevi chilometri di ferrovia da Klevan a Orzhiv in Ucraina, e tre chilometri nel famosissimo Tunnel dell’Amore, un intreccio di alberi e vegetazione che crea uno scenario suggestivo e romantico, quasi irreale, un luogo di promesse d’amore e baci rubati.','-una ferrovia da favola-','http://localhost/HW1/foto/pacchetti/europa/eu5.jpg','europa','4000'),
        ('La Circumetnea','Un modo originale per visitare uno dei simboli siciliani: l’Etna. La storica ferrovia è stata inaugurata nel 1898 e viaggia intorno al vulcano attraversando numerosi paesini, regalando ai viaggiatori pittoreschi scorci di questo paesaggio unico.','-tra i paesaggi lavici-','http://localhost/HW1/foto/pacchetti/europa/eu6.jpg','europa','1500');
        

INSERT INTO `TRENO` (`capienza_massima`, `velocita_massima`, `anno`, `tipologia`,`nome`,`descrizione`,`immagine`)
VALUES
	(370,null,1982,'Antico','VENICE SIMPLON - ORIENT EXPRESS',"Gli amanti del glamour andranno in brodo di giuggiole da Venezia a Londra. Il lusso trionfa, dall'arredo sontuoso del vagone ristorante (argenteria francese, tovaglie di lino e bicchieri di cristallo) al vagone piano bar,Signore, le scarpe di Manolo Blahnik sono l'ideale per fare la passerella nelle cittàpiù romantiche d'Europa che l'Orient Express degna con la sua presenza: Vienna, Parigi, Praga e Istanbul.",'http://localhost/HW1/foto/foto2/VENICE%20SIMPLON%20-%20ORIENT%20EXPRESS.jpg'),
	(190,null,1982,'Antico','GHAN', "La saga del Ghan ebbe inizio nel 1877, quando l'originale linea ferroviaria Adelaide-Alice Springs-Darwin fu costruita nel posto sbagliato. Nel corso del suo primo secolo di vita attraversava una pianura alluvionale, Dopo le piogge spesso i convogli si impantanavano nell'outback. Nel 1980 si inaugurò una linea alternativa che collega il temperato sud dell'Australia con il tropicale nord",'http://localhost/HW1/foto/foto2/GHAN.jpg'),
	(150,null,1982,'Antico','FERROCARRIL CHIHUAHUA PACÍFICO', "Il Ferrocarril Chihuahua Pacífico vanta 36 ponti e 87 gallerie distribuite su 655 km di binari. Collega il montuoso entroterra del Messico settentrionale con la costa del Pacifico, attraversando canyon dalle pareti verticali, cascate e pianure quasi desertiche. Sono due i treni che servono questa tratta tra Los Mochis e Chihuahua: il primera express (il treno di prima classe) dispone di un ristorante, di un bar e di sedili reclinabili, e fa meno fermate del clase economica.", 'http://localhost/HW1/foto/foto2/FERROCARRIL%20CHIHUAHUA%20PAC%c3%8dFICO.jpg'),
	(170,null,1982,'Antico','OUTENIQUA CHOO-TJOE', "In funzione dal 1928, questo treno a vapore procede scoppiettando senza fretta. Da Knysna sbuffa lungo la costa dell'Oceano Indiano, passa dalla città di Wilderness, con le sue ampie spiagge, attraversa il Kaimans Bridge e, ansimando, affronta la gola che porta a George. Il viaggio, andata e ritorno, dura circa 7 ore e mezzo",'http://localhost/HW1/foto/foto2/OUTENIQUA%20CHOO-TJOE.jpg'),
	(290,null,1982,'Antico','EL NARIZ DEL DIABLO', "Andando verso sud da Riobamba, la ferrovia conosciuta come El Nariz del Diablo (il naso del diavolo) collega Alausí a Sibambe. I lavori di costruzione iniziarono nel 1908 quando vennero scavati i tornanti che avrebbero permesso al treno di coprire i quasi 1000 m di dislivello che separano Sibambe da Alausí, quota 2607 m. I più spericolati affrontano il naso del diavolo sul tetto del treno. Ma lo spazio tra il loro sombrero e la volta delle gallerie è davvero scarso",'http://localhost/HW1/foto/foto2/EL%20NARIZ%20DEL%20DIABLO.jpg'),
	(390,null,1982,'Antico','TRANSIBERIANA', "Parte ogni martedì dalla stazione di Yaroslavl di Mosca, attraversa un terzo del pianeta e conclude la sua corsa nell'affascinante e decadente Vladivostok. Costeggia il Lago Baikal, che sembra apparire dal nulla in mezzo alla taiga siberiana, Deviando dalla linea principale, la transmongolica attraversa un paesaggio di tipiche abitazioni russe e distese di foreste che cedono il passo alle infinite steppe e ai cieli della Mongolia. Il treno prosegue poi fino a Pechino, passando dalla spettacolare Grande Muraglia.",'http://localhost/HW1/foto/foto2/TRANSIBERIANA.jpg'),
	(450,null,1982,'Antico','ROCKY MOUNTAINEER', "Questo treno attraversa in due giorni le incantevoli Canadian Rockies (Montagne Rocciose canadesi). Si viaggia di giorno, in modo da ammirare canyon, fiumi, valli e laghi glaciali. Si parte dalla costiera Vancouver. Poi si entra nel regno delle Rockies passando da Jasper, Banff e Calgary fino a raggiungere l'Albertaj",'http://localhost/HW1/foto/foto2/ROCKY%20MOUNTAINEER.jpg'),
	(175,null,1982,'Antico','COAST STARLIGHT', "Attraverso la costa occidentale degli Stati Uniti, la Starlight tocca alcune tra le città più importanti del paese: Seattle, Portland e Los Angeles. Il viaggio dura 35 ore e tocca tre stati: Washington, Oregon e California.",'http://localhost/HW1/foto/foto2/COAST%20STARLIGHT.jpg');
